/**
 * This file lists all Minecraft advancements as of version 1.21.10.
 *
 * Note that older Minecraft versions may not have all of these advancements
 * or use different identifiers.
 *
 * @see https://minecraft.fandom.com/wiki/Advancement
 */

const MINECRAFT_ADVANCEMENTS_STORY = [
  "story/root",
  "story/mine_stone",
  "story/upgrade_tools",
  "story/smelt_iron",
  "story/obtain_armor",
  "story/lava_bucket",
  "story/iron_tools",
  "story/deflect_arrow",
  "story/form_obsidian",
  "story/mine_diamond",
  "story/enter_the_nether",
  "story/shiny_gear",
  "story/enchant_item",
  "story/cure_zombie_villager",
  "story/follow_ender_eye",
  "story/enter_the_end",
] as const;

const MINECRAFT_ADVANCEMENTS_NETHER = [
  "nether/root",
  "nether/return_to_sender",
  "nether/find_bastion",
  "nether/obtain_ancient_debris",
  "nether/fast_travel",
  "nether/find_fortress",
  "nether/obtain_crying_obsidian",
  "nether/distract_piglin",
  "nether/ride_strider",
  "nether/uneasy_alliance",
  "nether/loot_bastion",
  "nether/netherite_armor",
  "nether/get_wither_skull",
  "nether/obtain_blaze_rod",
  "nether/charge_respawn_anchor",
  "nether/ride_strider_in_overworld_lava",
  "nether/explore_nether",
  "nether/summon_wither",
  "nether/brew_potion",
  "nether/create_beacon",
  "nether/all_potions",
  "nether/create_full_beacon",
  "nether/all_effects",
] as const;

const MINECRAFT_ADVANCEMENTS_THE_END = [
  "end/root",
  "end/kill_dragon",
  "end/dragon_egg",
  "end/enter_end_gateway",
  "end/respawn_dragon",
  "end/dragon_breath",
  "end/find_end_city",
  "end/elytra",
  "end/levitate",
] as const;

const MINECRAFT_ADVANCEMENTS_ADVENTURE = [
  "adventure/root",
  "adventure/voluntary_exile",
  "adventure/spyglass_at_parrot",
  "adventure/use_lodestone",
  "adventure/kill_a_mob",
  "adventure/read_power_of_chiseled_bookshelf",
  "adventure/trade",
  "adventure/trim_with_any_armor_pattern",
  "adventure/honey_block_slide",
  "adventure/ol_betsy",
  "adventure/lightning_rod_with_villager_no_fire",
  "adventure/fall_from_world_height",
  "adventure/salvage_sherd",
  "adventure/avoid_vibration",
  "adventure/sleep_in_bed",
  "adventure/hero_of_the_village",
  "adventure/spyglass_at_ghast",
  "adventure/throw_trident",
  "adventure/kill_mob_near_sculk_catalyst",
  "adventure/shoot_arrow",
  "adventure/kill_all_mobs",
  "adventure/totem_of_undying",
  "adventure/summon_iron_golem",
  "adventure/trade_at_world_height",
  "adventure/trim_with_all_exclusive_armor_patterns",
  "adventure/two_birds_one_arrow",
  "adventure/whos_the_pillager_now",
  "adventure/arbalistic",
  "adventure/craft_decorated_pot_using_only_sherds",
  "adventure/adventuring_time",
  "adventure/play_jukebox_in_meadows",
  "adventure/walk_on_powder_snow_with_leather_boots",
  "adventure/spyglass_at_dragon",
  "adventure/very_very_frightening",
  "adventure/sniper_duel",
  "adventure/bullseye",
] as const;

const MINECRAFT_ADVANCEMENTS_HUSBANDRY = [
  "husbandry/root",
  "husbandry/safely_harvest_honey",
  "husbandry/place_dried_ghast_in_water",
  "husbandry/breed_an_animal",
  "husbandry/allay_deliver_item_to_player",
  "husbandry/ride_a_boat_with_a_goat",
  "husbandry/tame_an_animal",
  "husbandry/make_a_sign_glow",
  "husbandry/fishy_business",
  "husbandry/silk_touch_nest",
  "husbandry/tadpole_in_a_bucket",
  "husbandry/obtain_sniffer_egg",
  "husbandry/plant_seed",
  "husbandry/wax_on",
  "husbandry/bred_all_animals",
  "husbandry/allay_deliver_cake_to_note_block",
  "husbandry/complete_catalogue",
  "husbandry/tactical_fishing",
  "husbandry/leash_all_frog_variants",
  "husbandry/feed_snifflet",
  "husbandry/balanced_diet",
  "husbandry/obtain_netherite_hoe",
  "husbandry/wax_off",
  "husbandry/axolotl_in_a_bucket",
  "husbandry/froglights",
  "husbandry/plant_any_sniffer_seed",
  "husbandry/kill_axolotl_target",
] as const;

const MINECRAFT_ADVANCEMENTS_ALL = [
  ...MINECRAFT_ADVANCEMENTS_STORY,
  ...MINECRAFT_ADVANCEMENTS_NETHER,
  ...MINECRAFT_ADVANCEMENTS_THE_END,
  ...MINECRAFT_ADVANCEMENTS_ADVENTURE,
  ...MINECRAFT_ADVANCEMENTS_HUSBANDRY,
] as const;

export {
  MINECRAFT_ADVANCEMENTS_STORY,
  MINECRAFT_ADVANCEMENTS_NETHER,
  MINECRAFT_ADVANCEMENTS_THE_END,
  MINECRAFT_ADVANCEMENTS_ADVENTURE,
  MINECRAFT_ADVANCEMENTS_HUSBANDRY,
  MINECRAFT_ADVANCEMENTS_ALL,
};
